### ISSUE TITLE
Missing SONAME

### ISSUE THREAD

**Issue by jspricke** [ros/roscpp_core#13]
Hi,

could you please add an SONAME to the libs?

Thanks!

Jochen

**Comment by dirk-thomas** [comment]
Non of the ROS packages currently defines SOVERSIONs for its libraries. And this is not likely to change in the near future.

There was some discussion on this topic on the buildsystem mailing list some time ago but without any consensus on how to go ahead with that. Since the SO version does not correlate with the package version it is not possible  to generate them easily.

**Comment by thomas-moulard** [comment]
Actually if you want to do this properly, independently of your system it will take an human to compute this number IMHO. However, as a first approximation what about putting 0 as SOVERSION and setting VERSION to the project version?

**Comment by dirk-thomas** [comment]
Until there is a REP which describes the policy for library versions this won't be implemented. Please consider starting a discussion on the buildsystem mailing list (ros-sig-buildsystem@googlegroups.com) or even better propose a REP.

I will mark this ticket as `wontfix` for now but it can be reopened as soon as a clear definition has been found.
