### ISSUE TITLE
Release pending: roscpp_core 0.3.13

### ISSUE THREAD

**Issue by ahendrix** [ros/roscpp_core#9]
Release should include fixes from #8

(I'm going to try creating a meta-issue for the release, as described on the mailing list, and see how it goes)

**Comment by dirk-thomas** [comment]
Please do not create tickets for releases. If that should be tracked it should be done with a milestone.

The current state can only be released as soon as we have kicked of hydro since we can not effort to run multiple full builds on the farm at the same time. It will very likely we released over the upcoming weekend.
